mydjango/apps/REST/urls.py
# apps.REST.urls
from django.conf.urls import url, patterns
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = format_suffix_patterns(patterns('',
    # REST API entry page  
    url(r'^$', 'api_root'),

    # endpoint for the api base view
    url(r'^api-auth/',
        namespace='REST')
))

mydjango/apps/authengine/urls.py
# apps.authengine.urls
from django.conf.urls import patterns, url
from django.contrib.auth import views


urlpatterns = patterns('',
    # login page 
    url(r'^login/$', 'login', {'template_name': 'authengine.login.html'},
        name='mydjango_login'),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'authengine/login.html'}),

    # landing page for logout
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='mydjango_logout'),
)

mydjango/apps/snippets/urls.py
# apps.snippets.urls
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from apps.snippets import views


urlpatterns = format_suffix_patterns(patterns('snippets.views',
    # list of snippets page
    url(r'^snippets/$',
        views.SnippetList.as_view(),
        name='snippet-list'),

    # details of a snippet page
    url(r'^snippets/(?P<pk>[0-9]+)/$',
        views.SnippetDetail.as_view(),
        name='snippet-detail'),

    # the highlighted view of the snippet page
    url(r'^snippets/(?P<pk>[0-9]+)/highlight/$',
        views.SnippetHighlight.as_view(),
        name='snippet-highlight'),

    # list of users page
    url(r'^users/$',
        views.UserList.as_view(),
        name='user-list'),

    # single user detail page
    url(r'^users/(?P<pk>[0-9]+)/$',
        views.UserDetail.as_view(),
        name='user-detail')
))

mydjango/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required as auth
from django.conf.urls import patterns, include, url
from django.conf import settings
from apps.linkengine.views import UserProfileDetailView, UserProfileEditView
from apps.linkengine.views import VoteFormView, LinkUpdateView, LinkDeleteView

# See: https://docs.djangoproject.com/en/dev/ref/contrib/admin/
#hooking-adminsite-instances-into-your-urlconf
admin.autodiscover()


# See: https://docs.djangoproject.com/en/dev/topics/http/urls/
urlpatterns = patterns('',
    # Admin panel and documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Login landing page
    url(r'^login/$', 'django.contrib.auth.views.login', {
    'template_name': 'registration/login.html'}, name="login"),

    # logout landing page
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
    name="logout"),

    # Accounts landing page
    url(r'^accounts/', include('registration.backends.simple.urls')),

    # User Profile Page
    url(r'^users/(?P<slug>\w+)/$', UserProfileDetailView.as_view(), name="profile"),

    # Edit user profile
    url(r'^edit_profile/$', (UserProfileEditView.as_view()), name="edit_profile"),


    # Blog URLs
    url(r'', include('apps.blogengine.urls')),

    # Flat pages
    url(r'^flat/', include('django.contrib.flatpages.urls')),

    # Links pages
    url(r'', include('apps.linkengine.urls')),

    url(r'^link/update/(?P<pk>\d+)/$', (LinkUpdateView.as_view()),
        name='link_update'),

    url(r'^link/delete/(?P<pk>\d+)/$', (LinkDeleteView.as_view()),
        name='link_delete'),

    # vote page
    url(r'^vote/$', (VoteFormView.as_view()), name="vote"),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

mydjango/apps/authengine/models.py
from django.db import models

# Create your models here.

mydjango/apps/blogengine/models.py
#blogengine.models

from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(max_length=40, unique=True, blank=True, null=True)

    def save(self):
        if not self.slug:
            self.slug = slugify(unicode(self.name))
        super(Category, self).save()

    def get_absolute_url(self):
        return "/category/%s/" % (self.slug)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Tag(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(max_length=40, unique=True, blank=True, null=True)

    def save(self):
        if not self.slug:
            self.slug = slugify(unicode(self.name))
        super(Tag, self).save()

    def get_absolute_url(self):
        return "/tag/%s/" % (self.slug)

    def __unicode__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    text = models.TextField()
    slug = models.SlugField(max_length=40, unique=True)
    author = models.ForeignKey(User)
    site = models.ForeignKey(Site)
    category = models.ForeignKey(Category, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)

    def get_absolute_url(self):
        return "/blogpost/%s/%s/%s/%s/" % (self.pub_date.year, self.pub_date.month, self.pub_date.day, self.slug)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["-pub_date"]

mydjango/apps/linkengine/models.py
# apps.linkengine.models
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.timezone import now


class LinkVoteCountManager(models.Manager):
    def get_query_set(self):
        return super(LinkVoteCountManager, self).get_query_set().annotate(
            votes=Count('vote')).order_by('-rank_score', '-votes')


class Link(models.Model):
    title = models.CharField("Headline", max_length=100)
    submitter = models.ForeignKey(User)
    sub_date = models.DateTimeField(auto_now_add=True)
    rank_score = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=250, blank=True)
    description = models.TextField(blank=True)
    with_votes = LinkVoteCountManager()
    objects = models.Manager()  # default manager

    def get_absolute_url(self):
        return reverse("link_detail", kwargs={"pk": str(self.id)})

    def set_rank(self):
        # Based on HN ranking algo at http://amix.dk/blog/post/19574
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.submitted_on
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()

    def __unicode__(self):
        return self.title


class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.link.title)


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    bio = models.TextField(null=True)

    def __unicode__(self):
        return "%s's profile" % self.user


def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

# Signal while saving user
from django.db.models.signals import post_save
post_save.connect(create_profile, sender=User)

mydjango/apps/snippets/models.py
# apps.snippets.models
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()
    linenos = models.BooleanField(default=False)
    language = models.CharField(choices=LANGUAGE_CHOICES,
                                default='python',
                                max_length=100)
    style = models.CharField(choices=STYLE_CHOICES,
                             default='friendly',
                             max_length=100)
    owner = models.ForeignKey('auth.User', related_name='snippets')
    highlighted = models.TextField()

    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        # Use the `pygments` library to create a highlighted HTML
        # representation of the code snippet.

        lexer = get_lexer_by_name(self.language)
        linenos = self.linenos and 'table' or False
        options = self.title and {'title': self.title} or {}
        formatter = HtmlFormatter(style=self.style, linenos=linenos,
                                  full=True, **options)
        self.highlighted = highlight(self.code, lexer, formatter)
        super(Snippet, self).save(*args, **kwargs)

        # limit the number of instances retained
        # snippets = Snippet.objects.all()
        # if len(snippets) > 100:
        # snippets[0].delete()

mydjango/apps/linkengine/forms.py
# apps.linkengine.forms
from django import forms
from models import UserProfile, Link, Vote


# use generic model to start User Profile
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ("user",)


# use generic form for links
class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submitter", "rank_score")


# toggle for vote/no vote on a link
class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote

mydjango/apps/authengine/views.py
from django.shortcuts import render

# Create your views here.

mydjango/apps/blogengine/views.py
# apps.blogengine.views
from django.shortcuts import render
from django.views.generic import ListView
from apps.blogengine.models import Category, Post, Tag
from django.contrib.syndication.views import Feed


# Create your views here.
class CategoryListView(ListView):
    def get_queryset(self):
        slug = self.kwargs['slug']
        try:
            category = Category.objects.get(slug=slug)
            return Post.objects.filter(category=category)
        except Category.DoesNotExist:
            return Post.objects.none()


class TagListView(ListView):
    def get_queryset(self):
        slug = self.kwargs['slug']
        try:
            tag = Tag.objects.get(slug=slug)
            return tag.post_set.all()
        except Tag.DoesNotExist:
            return Post.objects.none()


class PostsFeed(Feed):
    title = "RSS feed - posts"
    link = "feeds/posts/"
    description = "RSS feed - blog posts"

    def items(self):
        return Post.objects.order_by('-pub_date')

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.text

mydjango/apps/linkengine/views.py
# apps.links.views
from django.views.generic import ListView, DetailView
from django.views.generic import UpdateView, DeleteView
from django.views.generic.edit import CreateView, FormView
from apps.linkengine.models import Link, UserProfile, Vote
from django.contrib.auth import get_user_model
from apps.linkengine.forms import UserProfileForm, LinkForm, VoteForm
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import redirect, get_object_or_404
import json
from django.http import HttpResponse


# list of links
class LinkListView(ListView):
    model = Link
    queryset = Link.with_votes.all()
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted
        return context




# Page to create a new link
class LinkCreateView(CreateView):
    model = Link
    form_class = LinkForm

    def form_valid(self, form):
        f = form.save(commit=False)
        f.rank_score = 0.0
        f.submitter = self.request.user
        f.save()

        return super(CreateView, self).form_valid(form)


# details on the link
class LinkDetailView(DetailView):
    model = Link


# edit and update ink
class LinkUpdateView(UpdateView):
    model = Link
    form_class = LinkForm


# Delete a link
class LinkDeleteView(DeleteView):
    model = Link
    success_url = reverse_lazy("home")


# vote and record votte status re said line
class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response


class VoteFormBaseView(FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, link=link)
        has_voted = (len(prev_votes) > 0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, link=link)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors}
        return self.create_response(ret, False)


# pass to voteview no need to change code in other parts
class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

mydjango/apps/snippets/views.py
# apps.snippets.views
from apps.snippets.models import Snippet
from apps.snippets.serializers import SnippetSerializer, UserSerializer
from apps.snippets.permissions import IsOwnerOrReadOnly
from rest_framework import renderers, generics, permissions
from rest_framework.response import Response
from django.contrib.auth.models import User


# list of snippets, and then check if it is available
class SnippetList(generics.ListCreateAPIView):
    queryset = Snippet.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = SnippetSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def pre_save(self, obj):
        obj.owner = self.request.user


class SnippetDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Snippet.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly)
    serializer_class = SnippetSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

    def pre_save(self, obj):
        obj.owner = self.request.user


class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class SnippetHighlight(generics.GenericAPIView):
    queryset = Snippet.objects.all()
    renderer_classes = (renderers.StaticHTMLRenderer,)

    def get(self, request, *args, **kwargs):
        snippet = self.get_object()
        return Response(snippet.highlighted)

mydjango/templates/linkengine/link_confirm_delete.html
{% extends "includes/base.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'link_delete' pk=object.pk %}">
  {% csrf_token %}
  <a href="{% url 'link_detail' pk=object.pk %}">Go back</a> 
  <p><input type="submit" value="Confirm deletion" /></p>
</form> 

{% endblock %}

mydjango/templates/linkengine/link_detail.html
{% extends "includes/base.html" %}

{% block content %}
	<h2><a href="{{ object.link }}">{{ object.title }}</a></h2>
		{% if object.submitter == user %}
 			<a href="{% url 'link_update' pk=object.pk %}">Edit</a> | 
			<a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
		{% endif %}

<p>Submitted by <a href='{% url "profile" slug=object.submitter%}'>{{ object.submitter }}</a></p>

<div class="desc">
  	{{ object.description }}
</div>

{% endblock %}

mydjango/templates/linkengine/link_detail2.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<style>
  #id_honeypot {
    display: none;
  }
</style>

<h2><a href="{{ object.link }}">{{ object.title }}</a></h2>
{% if object.submitter == user %}
  <a href="{% url 'link_update' pk=object.pk %}">Edit</a> | 
  <a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
{% endif %}

<div class="desc">
  {{ object.description }}
</div>

<div class="comments">
  <h3>Comments</h3>

  <div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next" 
	   value="{% url 'link_detail' pk=object.id %}" />
    <input type="submit" value="Add comment" id="id_submit" />
  </form>
{% else %}
  <p>Please <a href="{% url 'login' %}">log in
  </a> to leave a comment.</p>
{% endif %}
  </div>


  {% render_comment_list for object %}
</div>


{% endblock %}

mydjango/templates/linkengine/link_form.html
{% extends "includes/base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add">
</form>
{% endblock %}

mydjango/templates/linkengine/link_list.html
<!--templates.linkengine.link_list-->
{% extends "includes/base.html" %}

	{% block title %}
		MyLinks
	{% endblock %}

	{% block content %}
		<ol>
		{% for link in object_list %}
		<form method="post" action="{% url 'vote' %}" class="vote_form">
    		<li> [{{ link.votes }}]
    		{% csrf_token %}
    		<input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    		<input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    		{% if not user.is_authenticated %}
    		<button disabled title="Please login to vote">+</button>
		    {% elif link.pk not in voted %}
    		<button>+</button>
		    {% else %}
  			<button>-</button>
 		    {% endif %}
            <a href="{% url 'link_detail' pk=link.pk %}"><button></button>
		    <li>
		    <a href="{{ link.url }}">
		    <a href="{% url 'link_detail' pk=link.pk %}">
		    	<b>{{ link.title }}</b></a>
		    </li>
		</form>    
		{% endfor %}
		</ol>
		<ul class="pager">
        {% if page_obj.has_previous %}
        <li class="previous"><a href="/{{ page_obj.previous_page_number }}/">Previous Page</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="next"><a href="/{{ page_obj.next_page_number }}/">Next Page</a></li>
        {% endif %}
        </ul>
	{% endblock %}

mydjango/templates/linkengine/links.html
<!--templates.links.links-->
{% extends "includes.base.html" %}

{% block content %}
	<ol>
	{% for link in object_list %}
	    <li>
	    <a href="{{ link.url }}">
	      <b>{{ link.title }}</b>
	    </a>
	    </li>
	{% endfor %}
	</ol>
{% endblock %}

mydjango/templates/linkengine/links_list.html
<!--templates.links.links-->
{% extends "includes.base.html" %}

{% block content %}
	<ol>
	{% for link in object_list %}
	    <li>
	    <a href="{{ link.url }}">
	      <b>{{ link.title }}</b>
	    </a>
	    </li>
	{% endfor %}
	</ol>
{% endblock %}